Testcase for merge operator
sergiiz/RxBasicsKata pull request #6
Opened 2017-02-07 09:13 UTC by ritesh-singh

2017-02-08 07:11 UTC, sergiiz commented
Thanks for your PRs @ritesh-singh, I'll take a look later this week

2017-02-10 21:34 UTC, sergiiz requested changes

2017-02-10 21:34 UTC, sergiiz commented on rxkata/src/main/java/org/sergiiz/rxkata/CountriesService.java
> +    Observable<Long> combineAndReturnTheSumOfPopulation(Observable<Country> countryObservable1,
Rename: sumPopulationOfCountries

2017-02-10 21:34 UTC, sergiiz commented on rxkata/src/main/java/org/sergiiz/rxkata/CountriesService.java
> +    Single<Boolean> checkIfBothObservableEmitsSameItems(Observable<Country> countryObservable1,
Rename: areEmittingSameItems (better names are welcome)

2017-02-10 21:34 UTC, sergiiz commented on rxkata/src/test/java/org/sergiiz/rxkata/CountriesServiceSolvedTest.java
> +        // hint: use "map" operator
Please rename all tests according to the following pattern: rx_<Tested_Method_Name> with behaviour explanation divided by `_`, see other test cases names as example

2017-02-10 21:34 UTC, sergiiz commented on README.md
> +- SequenceEqual: determine whether two Observable emit the same sequence of items
typo Observable**s**

2017-02-10 21:34 UTC, sergiiz commented on rxkata/src/main/java/org/sergiiz/rxkata/CountriesService.java
> +    Single<Boolean> checkIfObservableEmitsGivenItem(List<Country> countries,
Rename: ifObservableEmitsGivenItem.
And I'm wondering if this case is important at all, have you faced real situations where you needed such check?

2017-02-11 17:31 UTC, ritesh-singh commented
Sure. I will do the required changes and push.

2017-02-12 07:51 UTC, ritesh-singh commented on rxkata/src/main/java/org/sergiiz/rxkata/CountriesService.java
> +    Single<Boolean> checkIfObservableEmitsGivenItem(List<Country> countries,
Actually no, i have added it just to test the 'contains' operator functionality.

2017-02-15 06:26 UTC, merged